# Generated by Django 5.2.4 on 2026-05-15 05:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_alter_user_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +7XXXXXXXXXX или 8XXXXXXXXXX', regex='^(\\+7|8)\\d{10}$')], verbose_name='Телефон'),
        ),
    ]
